###############################################################################
#   Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
###############################################################################
domains:
  -
    domainName: "A"
    priority: 1
    identityStoreConnectors:
    -
      connectorName: "JDBCIS1"
      attributeMappings:
      - http://wso2.org/claims/username: "username"
      - http://wso2.org/claims/firstName: "firstName"
      - http://wso2.org/claims/lastName: "lastName"
    -
      connectorName: "JDBCIS2"
      attributeMappings:
      - http://wso2.org/claims/email: "email"
      - http://wso2.org/claims/firstName: "firstName"
      - http://wso2.org/claims/lastName: "lastName"
  -
    domainName: "B"
    priority: 2
    identityStoreConnectors:
    -
      connectorName: "JDBCIS3"
      attributeMappings:
      - http://wso2.org/claims/username: "email"
      - http://wso2.org/claims/firstName: "firstName"
      - http://wso2.org/claims/lastName: "lastName"

